name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run type check
      run: npm run typecheck
    
    - name: Run tests
      run: npm test
      env:
        CI: true
        NODE_ENV: test
        NEXT_PUBLIC_SUPABASE_URL: 'https://example.supabase.co'
        NEXT_PUBLIC_SUPABASE_ANON_KEY: 'dummy-key'
        SERVICE_KEY: 'dummy-service-key'
        NEXT_PUBLIC_APP_URL: 'http://localhost:3000'
        NEXT_PUBLIC_DISABLE_AUTH: 'true'
        GITHUB_CLIENT_ID: 'test-client-id'
        GITHUB_CLIENT_SECRET: 'test-client-secret'
    
    - name: Build check
      run: npm run build
      env:
        NEXT_PUBLIC_SUPABASE_URL: 'https://example.supabase.co'
        NEXT_PUBLIC_SUPABASE_ANON_KEY: 'dummy-key'
        SUPABASE_SERVICE_ROLE_KEY: 'dummy-service-key'
        OPENAI_API_KEY: 'dummy-openai-key'
        NEXT_PUBLIC_APP_URL: 'http://localhost:3000'
        NEXT_PUBLIC_DISABLE_AUTH: 'true'
        GITHUB_CLIENT_ID: 'test-client-id'
        GITHUB_CLIENT_SECRET: 'test-client-secret'
        CRON_SECRET: 'dummy-cron-secret'